name: My First CI

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Start
        run: echo "Starting CI..."

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Show Java Version
        run: java -version

      - name: Print Finish
        run: echo "CI Completed Successfully!"