name: my-java-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      
      - name: verify java
        run: java -version
      
      - name: Final Build Project
        run: mvn clean package
    