name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Check Project Directory
        run: pwd

      - name: Check Project Files
        run: ls -la

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Check java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Run Project
        run: mvn clean package
        
      - name: Make Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Saving Artifacts
          path: target/*.jar

  
  docker:
    needs: build

    runs-on: ubuntu-latest

    steps:
       - name: Again Checkout for Docker
         uses: actions/checkout@v4

       - name: Downloading Artifacts from Build
         uses: actions/download-artifacts@v4
         with:
          name: Saving Artifacts
          path: target
        
       - name: Build Docker Image
         run: docker build -t mustafashaikh05/demo-project-img:latest .

       - name: Login to Docker Hub

         run: |
           echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

       - name: Push Image

         run: docker push mustafashaikh05/demo-project-img:latest



    



# name: ci pipeline

# on:
#   push:
#     branches:
#       - main
# jobs:
#   upload:

#     runs-on: ubuntu-latest

#     steps:
#       - name: clone project
#         uses: actions/checkout@v4
      
#       - name: Verify it
#         run: pwd
      
#       - name: List Files of Proejct
#         run: ls -la

#       - name: Download Java
#         uses: actions/setup-java@v4
#         with:
#           distribution: temurin
#           java-version: '21'
#           cache: maven
      
#       - name: verify Java
#         run: java -version

#       - name: verify Maven
#         run: mvn -version
      
#       - name: Run Maven
#         run: mvn clean package
          
#       - name: Save Artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: my-artifact
#           path: target/*.jar


# name: my-java-pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#       - name: clone repo
#         uses: actions/checkout@v4

#       - name: Install Java
#         uses: actions/setup-java@v4
#         with:
#           distribution: temurin
#           java-version: '21'
      
#       - name: verify java
#         run: java -version
      
#       - name: Final Build Project
#         run: mvn clean package
    